---
permalink: sm-storage/change-configuration-settings-for-a-volume-group.html 
sidebar: sidebar 
keywords: change, raid level, volume group 
summary: ボリュームグループにアクセスするアプリケーションに必要なパフォーマンスを確保できるように、ボリュームグループのRAIDレベルを変更することができます。この操作により、データI/Oに影響を与えることなく、ボリュームグループのRAIDレベルが変更されます 
---
= ボリュームグループのRAIDレベルを変更します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームグループにアクセスするアプリケーションに必要なパフォーマンスを確保できるように、ボリュームグループのRAIDレベルを変更することができます。この処理を実行すると、データのI/Oに影響を及ぼすことなく、ボリュームグループのRAIDレベルが変更されます

.作業を開始する前に
* ボリュームグループのステータスが最適である必要があります。
* ボリュームグループに、新しいRAIDレベルに変換するための十分な容量が必要です。
* プールのRAIDレベルは変更できません。System Managerはプールを自動的にRAID 6として構成します。


.このタスクについて
この処理は開始後にキャンセルすることはできません。データはこの処理の実行中も引き続き使用できます。

RAIDレベルについて

[cols="2*"]
|===
| RAIDレベル | 説明 


 a| 
RAID 0ストライピング
 a| 
ハイパフォーマンスを実現できますが、データの冗長性は確保されません。ボリュームグループ内の1本のドライブで障害が発生すると、関連付けられているすべてのボリュームで障害が発生し、すべてのデータが失われます。

ストライピングRAIDグループは、2つ以上のドライブを1つの大容量論理ドライブにまとめます。



 a| 
RAID 1ミラーリング
 a| 
ハイパフォーマンスと最高レベルのデータ可用性を提供し、企業レベルまたは個人レベルの機密データの格納に適しています。

一方のドライブの内容をミラーペアのもう一方のドライブに自動的にミラーリングすることで、データを保護します。単一のドライブ障害からの保護を提供します。



 a| 
RAID 10ストライピング/ミラーリング
 a| 
RAID 0（ストライピング）とRAID 1（ミラーリング）を組み合わせたもので、ドライブを4本以上選択した場合に実現されます。

RAID 10は、高いパフォーマンスとフォールトトレランスが必要な、データベースなどの大量のトランザクションを処理するアプリケーションに適しています。



 a| 
RAID 5
 a| 
標準的なI/Oサイズが小さく読み取り処理の割合が高いマルチユーザ環境（データベースやファイルシステムストレージなど）に最適です。



 a| 
RAID 6
 a| 
RAID 5を超える冗長性が求められるが高い書き込みパフォーマンスは必要がない環境に最適です。

|===
RAID 3をボリュームグループに割り当てるには、コマンドラインインターフェイスを使用する必要があります。

.手順
. 「* MENU（*メニュー）」：「Storage（プールとボリュームグループ）」*を選択します。
. 編集するボリュームグループを選択し、*表示/設定の編集*をクリックします。
+
ボリュームグループ設定(Volume Group Settings)ダイアログボックスが表示されます

. ドロップダウンリストからRAIDレベルを選択し、* Save *をクリックします。
+
RAIDレベルの変更によって容量が減ったり、ボリュームの冗長性が失われたり、シェルフ/ドロワー損失の保護が失われた場合は、確認ダイアログボックスが表示されます。続行するには*はい*を選択し、続行しない場合は*いいえ*をクリックします。



.結果
ボリュームグループのRAIDレベルを変更すると、ボリュームグループを構成するすべてのボリュームのRAIDレベルがSystem Managerによって変更されます。処理の実行中は、パフォーマンスが若干低下することがあります。
