---
permalink: sm-storage/create-synchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, synchronous, mirrored, volume 
summary: ボリュームを同期的にミラーリングしてデータをストレージアレイ間でリアルタイムにレプリケートすると、システムとサイトの両方の障害から情報が保護されます。そのためには、ローカルストレージアレイとリモートストレージアレイの間の同期ミラーリング関係で使用するプライマリボリュームとセカンダリボリュームを選択します。 
---
= 同期ミラーボリュームを作成する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームを同期的にミラーリングしてデータをストレージアレイ間でリアルタイムにレプリケートすると、システムとサイトの両方の障害から情報が保護されます。そのためには、ローカルストレージアレイとリモートストレージアレイの間の同期ミラーリング関係で使用するプライマリボリュームとセカンダリボリュームを選択します。

.作業を開始する前に
* 同期ミラーリング機能では複数のストレージアレイを管理する必要があるため、ブラウザベースのSANtricity Unified Managerをインストールし、データをミラーリングする2つのストレージアレイを検出しておく必要があります。次に、Unified Managerでプライマリボリュームのストレージアレイを選択し、* Launch *をクリックして、ブラウザベースのSANtricity システムマネージャを開きます。
* 2つのストレージアレイが必要です。
* 各ストレージアレイに2台のコントローラが必要です。
* プライマリボリュームとセカンダリボリュームのストレージアレイで異なるバージョンのOSを実行できます。サポートされる最小バージョンは7.84です。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ローカルとリモートのストレージアレイがFibre Channelファブリックを介して接続されている必要があります。
* 同期ミラー関係で使用するプライマリボリュームとセカンダリボリュームの両方を作成しておく必要があります。


.このタスクについて
ボリュームを同期的にミラーリングするプロセスは複数の手順で構成される手順 です。

* <<手順1：プライマリボリュームを選択します>>
* <<手順2：セカンダリボリュームを選択する>>
* <<手順3：同期設定を選択します>>


ボリュームに設定できるミラー関係は1つだけです。



== 手順1：プライマリボリュームを選択します

[role="lead"]
同期ミラー関係で使用するプライマリボリュームを選択する必要があります。このボリュームには、ミラー関係のプライマリロールが割り当てられます。

.作業を開始する前に
* 同期ミラー関係で使用するプライマリボリュームを作成しておく必要があります。
* プライマリボリュームは標準ボリュームである必要があります。シンボリュームやSnapshotボリュームは使用できません。


.手順
. 次のいずれかを実行して、同期ミラーリングの手順を開始します。
+
** メニューを選択します。Storage [Synchronous Mirroring > Mirror volume]。
** メニューを選択します。Storage [Volumes]、[Copy Services]、[Mirror a volume s[s方 を同期的にミラーリング]。同期ミラーペアの作成*ダイアログが表示されます。


. ミラーのプライマリボリュームとして使用する既存のボリュームを選択します。
+
[NOTE]
====
ボリュームをボリュームタイルで選択し、ミラーリングの対象になっている場合は、デフォルトでボリュームが選択されます。

====
. [次へ]を選択し、に進みます <<手順2：セカンダリボリュームを選択する>>。




== 手順2：セカンダリボリュームを選択する

[role="lead"]
ミラー関係で使用するセカンダリボリュームを選択する必要があります。このボリュームには、ミラー関係のセカンダリロールが割り当てられます。

.作業を開始する前に
* 同期ミラー関係で使用するセカンダリボリュームを作成しておく必要があります。
* セカンダリボリュームは標準ボリュームである必要があります。シンボリュームやSnapshotボリュームは使用できません。
* セカンダリボリュームには、プライマリボリュームと同等以上のサイズが必要です。


.このタスクについて
リモートストレージアレイのセカンダリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。使用できないボリュームはリストに表示されません。

このダイアログでは、ボリュームが容量でソートされ、プライマリボリュームの容量に最も近いボリュームから順番に表示されます。容量が同じ場合はアルファベット順に表示されます。

.手順
. ローカルストレージアレイとの間でミラー関係を確立するリモートストレージアレイを選択します。
+
[NOTE]
====
リモートストレージアレイがパスワードで保護されている場合は、パスワードの入力を求められます。

====
+
** ストレージアレイは、対応するストレージアレイ名別に表示されます。ストレージアレイに名前を付けていない場合は、「unnamed」と表示されます。
** 使用するストレージアレイがリストに表示されない場合は、SANtricity Storage ManagerのEnterprise Management Window（EMW）を使用して追加します。メニューを選択します。Edit [Add Storage Array]を選択します。


. ミラーのセカンダリボリュームとして使用する既存のボリュームを選択します。
+
[NOTE]
====
選択したセカンダリボリュームの容量がプライマリボリュームよりも大きい場合、使用可能な容量はプライマリボリュームのサイズまでに制限されます。

====
. 「*次へ*」をクリックして、に進みます <<手順3：同期設定を選択します>>。




== 手順3：同期設定を選択します

[role="lead"]
通信が中断した場合に、プライマリボリュームの所有コントローラがセカンダリボリュームとの間でデータを再同期する優先度を設定する必要があります。また、再同期ポリシーとして、手動または自動のどちらかを選択する必要があります。

.手順
. スライダバーを使用して同期優先度を設定します。
+
同期優先度は、I/O要求の処理と比較して、初期同期および通信中断後の再同期処理を完了するためにどの程度のシステムリソースが使用されるかを決定するものです。

+
このダイアログ環境 で設定した優先度。プライマリボリュームとセカンダリボリュームの両方に適用されます。プライマリボリュームの速度は、あとからメニューを選択して変更できます。Storage [Synchronous Mirroring > More > Edit Settings]を選択します。

+
.同期速度について
[%collapsible]
====
同期優先度は5段階で設定できます。

** 最低
** 低
** 中
** 高
** 最高-同期優先度が最低に設定されている場合はI/Oアクティビティが優先され、再同期処理にかかる時間が長くなります。同期優先度が最高に設定されている場合は再同期処理が優先されますが、ストレージアレイのI/Oアクティビティに影響する可能性があります。


====
. リモートストレージアレイのミラーペアの再同期を手動で行うか自動で行うかを選択します。
+
** *手動*（推奨オプション）-ミラーペアとの通信が回復したあとに同期を手動で再開する場合に選択します。このオプションを選択すると、最適なタイミングでデータをリカバリできます。
** *自動*--ミラーペアとの通信が回復した後、再同期を自動的に開始する場合に選択します。同期を手動で再開するには、メニュー：ストレージ[同期ミラーリング]に移動し、テーブルでミラーペアを強調表示して、[*その他*]の下の[*再開]を選択します。


. 完了*をクリックして、同期ミラーリングを完了します。


.結果
System Managerは次の処理を実行します。

* 同期ミラーリング機能をアクティブ化します。
* ローカルストレージアレイとリモートストレージアレイの間で初期同期を開始します。
* 同期優先度と再同期ポリシーを設定します。


.完了後
同期ミラーリング処理の進捗状況を表示するには、メニューHome（実行中の処理の表示）を選択します。この処理には時間がかかることがあり、システムのパフォーマンスに影響する可能性があります。
