---
permalink: sm-storage/what-is-data-assurance.html 
sidebar: sidebar 
keywords: data, assurance 
summary: Data Assurance（DA）は、ホストとストレージアレイの間でデータをやり取りするときに発生する可能性があるエラーをチェックして修正します。System Managerでは、DA機能はプールおよびボリュームグループのレベルで提供されます。 
---
= Data Assuranceとは何ですか？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Data Assurance（DA）は、ホストとストレージアレイの間でデータをやり取りするときに発生する可能性があるエラーをチェックして修正します。System Managerでは、DA機能はプールおよびボリュームグループのレベルで提供されます。

Data Assurance（DA）機能を使用すると、ストレージシステム全体のデータの整合性が向上します。ホストとドライブの間でデータが移動されたときにストレージアレイがエラーの有無をチェックします。この機能を有効にすると、ボリューム内の各データブロックに巡回冗長検査（CRC）と呼ばれるエラーチェック用のコードが付加されます。データブロックが移動されると、ストレージアレイはこれらのCRCコードを使用して、転送中にエラーが発生したかどうかを判断します。破損している可能性があるデータはディスクに書き込まれず、ホストにも返されません。

DA機能を使用する場合は、新しいボリュームを作成するときにDAに対応したプールまたはボリュームグループを選択します（プールとボリュームグループの候補テーブルでDAの横にある「* Yes *」と検索します）。

これらのDA対応ボリュームは、必ずDAに対応したI/Oインターフェイスを使用しているホストに割り当ててください。DAに対応したI/Oインターフェイスには、Fibre Channel、SAS、iSCSI over TCP/IP、iSER over InfiniBand（iSCSI Extensions for RDMA/IB）があります。SRP over InfiniBandではDAはサポートされていません。
