---
permalink: sm-mirroring/considerations-for-setting-up-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: considerations, setting up, asynchronous, mirror 
summary: 設定とセットアップを適切に行うために、いくつかの重要な考慮事項について計画段階から把握しておいてください。 
---
= 非同期ミラーリングのセットアップに関する考慮事項
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定とセットアップを適切に行うために、いくつかの重要な考慮事項について計画段階から把握しておいてください。



== SANtricity Unified Managerを起動します

* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* 非同期ミラーリングを設定するには、SANtricity Unified Managerを開きます。あらゆるミラーリング関係で、ローカルとリモートの両方のストレージシステムがSANtricity Unified Managerで検出されて表示されている必要があります。
* ブラウザベースのSANtricity Unified Managerをインストールし、データをミラーリングする2つのストレージアレイを検出しておく必要があります。次に、Unified Managerでプライマリボリュームのストレージアレイを選択し、Launchをクリックして、ブラウザベースのSANtricity System Managerを開きます。




== アクティブ化中です

非同期ミラーリングを使用するには、ミラーリング処理の対象となる各ストレージアレイでミラーリングをアクティブ化しておく必要があります。アクティブ化は、CLI、REST API、または管理グラフィカルユーザインターフェイス（GUI）を使用して実行できます。

* SANtricity System Managerで管理されるシステム（E2800、E5700、EF570）では、アクティブ化の手順を実行する必要はなく、ミラーグループまたはミラーペアの設定時にアクティブ化が実行されます。
* SANtricity Storage Managerで管理されるシステム（E2700、E5600、EF560）では、SANtricity System Managerで管理されない従来型システムのGUIを使用して非同期ミラーリングがアクティブ化されます。非同期ミラーリングにiSCSIを使用する場合は、アクティブ化の手順は必要ありません。




== Webサービスの証明書と推奨ブラウザ

* *信頼された証明書*
+
ミラーリングの対象にSANtricity System Managerで管理されるシステムが含まれる場合は、Webサーバへのストレージシステムの認証を許可する、Webサービスの信頼された証明書をSANtricity Unified Managerにインポートすることを推奨します。SANtricity Unified Managerでの手順は次のとおりです。

+
.. SANtricity Unified Managerがインストールされているマシンの証明書署名要求（CSR）を生成します。
.. CSRを認証局（CA）に送信します。
.. CAから返された署名済みの証明書をUnified Managerにインポートします。


* *自己署名証明書*
+
自己署名証明書を使用することもできます。署名済みの証明書をインポートせずにミラーリングを設定しようとすると、SANtricity System Managerにエラーダイアログボックスが表示されます。このダイアログボックスで自己署名証明書を承認することができます。この場合、最新バージョンのChromeまたはFirefoxをブラウザとして使用することを推奨します。

+
Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。





== サポートされる接続

非同期ミラーリングでは、ローカルとリモートのストレージシステム間の通信にFC接続、iSCSI接続、またはその両方を使用できます。ミラー整合性グループ（非同期ミラーグループ）を作成するときに、リモートストレージアレイに対してFCとiSCSIの両方の接続が確立されている場合は、そのグループでどちらを使用するかを選択することができます。あるチャネルタイプから別のチャネルタイプへのフェイルオーバーはありません。

非同期ミラーリングでは、ストレージアレイのホスト側のI/Oポートを使用して、プライマリ側からセカンダリ側にミラーデータが送信されます。

* * Fibre Channel（FC）インターフェイス経由のミラーリング*
+
ストレージアレイの各コントローラでは、最も番号が大きいFCホストポートがミラーリング処理の専用ポートとして使用されます。

+
ベースのFCポートとホストインターフェイスカード（HIC）のFCポートの両方があるコントローラでは、HICの最も番号が大きいポートが使用されます。専用ポートにログオンしたホストはログアウトされ、ホストログイン要求は許可されません。このポートでは、ミラーリング処理の対象となるコントローラからのI/O要求のみが許可されます。

+
専用のミラーリングポートは、ディレクトリサービスとネームサービスのインターフェイスをサポートするFCファブリック環境に接続されている必要があります。特に、FC-ALおよびポイントツーポイントはミラー関係が確立されたコントローラ間の接続オプションとしてサポートされないことに注意してください。

* * iSCSIインターフェイス経由のミラーリング*
+
FCとは異なり、iSCSIでは専用のポートを必要としません。iSCSI環境で非同期ミラーリングを使用する場合、ストレージアレイのどのフロントエンドiSCSIポートも非同期ミラーリング専用にする必要はありません。これらのポートは、非同期ミラーリングのトラフィックとホスト/アレイ間のI/O接続で共有されます。

+
コントローラはリモートストレージシステムのリストを管理しており、iSCSIイニシエータはこのリストを使用してセッションの確立を試みます。iSCSI接続の確立に成功した最初のポートは、そのリモートストレージアレイとの以降のすべての通信に使用されます。通信に失敗すると、使用可能なすべてのポートを使用して新しいセッションの確立が試行されます。

+
iSCSIポートは、アレイレベルでポート単位で設定します。設定メッセージおよびデータ転送用のコントローラ間通信では、次の設定を含むグローバル設定が使用されます。

+
** VLAN：ローカルシステムとリモートシステムが通信するためには、両方のシステムでVLAN設定が同じである必要があります
** iSCSIリスニングポート
** ジャンボフレーム
** イーサネットの優先順位


+
[NOTE]
====
コントローラ間のiSCSI通信には、管理イーサネットポートではなくホスト接続ポートを使用する必要があります。

====


非同期ミラーリングでは、ストレージアレイのホスト側のI/Oポートを使用して、プライマリ側からセカンダリ側にミラーデータが送信されます。非同期ミラーリングは高レイテンシで低コストのネットワーク向けの機能であるため、iSCSI接続（TCP / IPベースの接続）が適しています。iSCSI環境で非同期ミラーリングを使用する場合、アレイのどのフロントエンドiSCSIポートも非同期ミラーリング専用にする必要はありません。これらのポートは、非同期ミラーリングのトラフィックとホスト/アレイ間のI/O接続で共有されます
