---
permalink: sm-mirroring/create-asynchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, asynchronous, mirrored, volume 
summary: ボリュームを非同期でミラーリングすることで、リモートストレージアレイのデータをローカルストレージアレイの特定の時点のデータと整合性がとれた状態に維持することができます。そのためには、ミラー整合性グループを作成して2つのストレージアレイ間にミラーリング関係を確立し、ミラーに使用するプライマリボリュームとセカンダリボリュームを選択します。 
---
= 非同期ミラーボリュームを作成します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームを非同期でミラーリングすることで、リモートストレージアレイのデータをローカルストレージアレイの特定の時点のデータと整合性がとれた状態に維持することができます。そのためには、ミラー整合性グループを作成して2つのストレージアレイ間にミラーリング関係を確立し、ミラーに使用するプライマリボリュームとセカンダリボリュームを選択します。

.作業を開始する前に
* 次の条件を満たしている必要があります。
+
** Web Services Proxyサービスが実行されている。
** SANtricity Unified ManagerがHTTPS接続経由でローカルホストで実行されている。
** プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
** SANtricity Unified Managerにストレージアレイの有効なSSL証明書が表示されています。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。
** SANtricity System ManagerがUnified Managerから起動されている。
** データをミラーリングする2つのストレージアレイを検出しておく必要があります。次に、Unified Managerでプライマリボリュームのストレージアレイを選択し、Launchをクリックして、ブラウザベースのSANtricity System Managerを開きます。


* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ローカルとリモートのストレージアレイがFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続されている必要があります。


ボリュームを非同期でミラーリングするプロセスは複数の手順で構成される手順 です。

*  1: Create a mirror consistency group or select an existing one
*  2: Select the primary volume
*  3: Select the secondary volume


ボリュームに設定できるミラー関係は1つだけです。



== 手順1：ミラー整合性グループを作成するか既存のグループを選択します

[role="lead"]
ミラー整合性グループを作成するか既存のグループを選択して、ローカルストレージアレイとリモートストレージアレイの間にミラーリング関係を確立します。

作成できるミラー整合性グループ関係とミラーペア関係の数は、ストレージアレイのハードウェアによって異なります。

.手順
. 次のいずれかを実行して、非同期ミラーリングの手順を開始します。
+
** メニューを選択します。Storage [非同期ミラーリング]>[ミラーペアの作成]。
** メニューを選択します。Storage [Volumes]、[Copy Services]、[Mirror a volume非同期]の順に選択します。


. 既存のミラー整合性グループを選択するか、新規に作成します。
+
新しいミラー整合性グループを作成するには、次の手順を実行します。

+
.. 2つのストレージアレイ間でミラーリングするボリューム上のデータに最も近い一意の名前（R&Dデータなど）を入力します。
.. ローカルストレージアレイとの間でミラー関係を確立するリモートストレージアレイを選択します。
+
[NOTE]
====
リモートストレージアレイがパスワードで保護されている場合は、パスワードの入力を求められます。

====
.. リモートストレージアレイのミラーペアの再同期を手動で行うか自動で行うかを選択します。
+
*** *手動*--手動再同期メニューオプションを使用して'セカンダリ・ポイント・イン・タイム・イメージを明示的に更新する必要がありますこのオプションは、非同期ミラーグループ内のすべての非同期ミラーペアの再同期を手動で開始する場合に選択します。
*** *自動*--ドロップダウンを使用して'前回の更新の開始から次の更新の開始までの時間を指定します自動同期の間隔をデフォルトの10分から変更するには、間隔の値を分単位で定義します。


.. Create をクリックします。 .
+
System Managerによって、最初にローカルストレージアレイに、続いてリモートストレージアレイにミラー整合性グループが作成されます。

+
[NOTE]
====
System Managerによるミラー整合性グループの作成がローカルストレージアレイで成功したあと、リモートストレージアレイで失敗した場合は、ローカルストレージアレイからミラー整合性グループが自動的に削除されます。System Managerによるミラー整合性グループの削除でエラーが発生した場合は、手動で削除する必要があります。

====


. [次へ]を選択し、に進みます  2: Select the primary volume。




== 手順2：プライマリボリュームを選択する

[role="lead"]
ミラー関係で使用するプライマリボリュームを選択し、リザーブ容量を割り当てる必要があります。ローカルストレージアレイのミラー整合性グループに追加したボリュームには、ミラー関係のプライマリロールが割り当てられます。

.手順
. ミラーのプライマリボリュームとして使用する既存のボリュームを選択し、* Next *をクリックしてリザーブ容量を割り当てます。
. 選択したプライマリボリュームにリザーブ容量を割り当てます。次のいずれかを実行します。
+
** *デフォルト設定を受け入れます*-この推奨オプションを使用して、プライマリボリュームのリザーブ容量をデフォルト設定で割り当てます。
** *データストレージの非同期ミラーリングのニーズに合わせて独自の設定でリザーブ容量を割り当てる*--次のガイドラインに従ってリザーブ容量を割り当てます
+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の20%であり、通常はこの容量で十分です。
*** 必要な容量は、プライマリボリュームに対するI/O書き込みの頻度とサイズ、およびその容量を維持する必要がある期間によって異なります。
*** 一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量を大きくします。
+
**** ミラーペアを長期にわたって維持する場合。
**** 大量のI/Oアクティビティにより、プライマリボリュームのデータブロックの大部分で変更が発生する場合。プライマリボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。






. [次へ]を選択し、に進みます  3: Select the secondary volume。




== 手順3：セカンダリボリュームを選択する

[role="lead"]
ミラー関係で使用するセカンダリボリュームを選択し、リザーブ容量を割り当てる必要があります。リモートストレージアレイのミラー整合性グループに追加したボリュームには、ミラー関係のセカンダリロールが割り当てられます。

リモートストレージアレイのセカンダリボリュームを選択すると、そのミラーペアに対応するすべてのボリュームのリストが表示されます。使用できないボリュームはリストに表示されません。

.手順
. ミラーペアのセカンダリボリュームとして使用する既存のボリュームを選択し、* Next *をクリックしてリザーブ容量を割り当てます。
. 選択したセカンダリボリュームにリザーブ容量を割り当てます。次のいずれかを実行します。
+
** *デフォルト設定を受け入れます*-この推奨オプションを使用して、セカンダリボリュームのリザーブ容量をデフォルト設定で割り当てます。
** *データストレージの非同期ミラーリングのニーズに合わせて独自の設定でリザーブ容量を割り当てる*--次のガイドラインに従ってリザーブ容量を割り当てます
+
*** リザーブ容量のデフォルト設定はベースボリュームの容量の20%であり、通常はこの容量で十分です。
*** 必要な容量は、プライマリボリュームに対するI/O書き込みの頻度とサイズ、およびその容量を維持する必要がある期間によって異なります。
*** 一般に、次のいずれかまたは両方に該当する場合は、リザーブ容量を大きくします。
+
**** ミラーペアを長期にわたって維持する場合。
**** 大量のI/Oアクティビティにより、プライマリボリュームのデータブロックの大部分で変更が発生する場合。プライマリボリュームに対する一般的なI/Oアクティビティを判断するには、過去のパフォーマンスデータやその他のオペレーティングシステムユーティリティを使用します。






. 「* Finish *」を選択して、非同期ミラーリングのシーケンスを完了します。


System Managerは次の処理を実行します。

* ローカルストレージアレイとリモートストレージアレイの間で初期同期を開始します。
* ミラーリングしているボリュームがシンボリュームの場合、初期同期では、プロビジョニングされたブロック（レポート容量ではなく割り当て容量）のみがセカンダリボリュームに転送されます。これにより、初期同期を完了するために転送する必要があるデータの量が削減されます。
* ローカルストレージアレイとリモートストレージアレイにミラーペア用のリザーブ容量を作成します。

