---
permalink: sm-mirroring/requirements-for-using-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: requirements, use, asynchronous, mirroring 
summary: 非同期ミラーリング機能を使用する場合は、次の要件に注意してください。 
---
= 非同期ミラーリングを使用するための要件
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
非同期ミラーリング機能を使用する場合は、次の要件に注意してください。



== SANtricity Unified Manager の略

非同期ミラーリングを使用するには、次の条件を満たしている必要があります。

* Web Services Proxyサービスが実行されている。
* SANtricity Unified ManagerがHTTPS接続経由でローカルホストで実行されている。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* SANtricity Unified Managerにストレージアレイの有効なSSL証明書が表示されています。Unified Managerのメニューから「Certificate Management」に移動し、自己署名証明書を受け入れるか、独自のセキュリティ証明書をインストールできます。
* SANtricity System ManagerがUnified Managerから起動されている。
* データをミラーリングする2つのストレージアレイを検出しておく必要があります。次に、Unified Managerでプライマリボリュームのストレージアレイを選択し、* Launch *をクリックして、ブラウザベースのSANtricity システムマネージャを開きます。




== ストレージアレイ

* 2つのストレージアレイが必要です。
* プライマリアレイとセカンダリアレイの各コントローラにイーサネット管理ポートが設定されていて、各コントローラがネットワークに接続されている必要があります。
* 各ストレージアレイに2台のコントローラが必要です。
* プライマリボリュームとセカンダリボリュームのストレージアレイで異なるバージョンのOSを実行できます。サポートされる最小バージョンは7.84です。
* ローカルとリモートのストレージアレイのパスワードを確認しておく必要があります。
* ミラーリングするプライマリボリューム以上のセカンダリボリュームを作成するには、リモートストレージアレイに十分な空き容量が必要です。
* ローカルとリモートのストレージアレイがFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続されている必要があります。




== サポートされるハードウェア構成と接続の要件

* 非同期ミラーリングは、デュアルコントローラのハードウェア構成でのみサポートされます。
* 非同期ミラーリング機能の通信は、Fibre Channel（FC）ホストポートまたはiSCSIホストポートを搭載したコントローラでのみサポートされます。この機能では、ローカルストレージアレイとリモートストレージアレイの両方にある各コントローラのいずれかのホストポートが使用されます。
* ストレージアレイがFC接続とiSCSI接続の両方で接続されている場合は、1つの非同期ミラーグループをFC経由でミラーリングし、別の非同期ミラーグループをiSCSI経由でミラーリングできます。




== ミラーボリュームの候補

* 非同期ミラーペアのプライマリボリュームとセカンダリボリュームでは、RAIDレベル、キャッシングパラメータ、およびセグメントサイズが異なる場合があります。
* セカンダリボリュームには、プライマリボリュームと同等以上のサイズが必要です。
* ボリュームに設定できるミラー関係は1つだけです。




== リザーブ容量

* コントローラのリセットおよびその他の一時的な中断からリカバリするための書き込み情報をログに記録するには、ミラーペアのプライマリボリュームとセカンダリボリュームにリザーブ容量ボリュームが必要です。
* ミラーペアのプライマリボリュームとセカンダリボリュームには追加のリザーブ容量が必要であるため、ミラー関係にある両方のストレージアレイに空き容量が確保されていることを確認してください。




== ドライブセキュリティ機能

* セキュリティ対応ドライブを使用する場合、プライマリボリュームとセカンダリボリュームのセキュリティ設定に互換性がある必要があります。この制限は強制的には適用されないため、自分で確認する必要があります。
* セキュリティ対応ドライブを使用する場合、プライマリボリュームとセカンダリボリュームで同じタイプのドライブを使用する必要があります。この制限は強制的には適用されないため、自分で確認する必要があります。
* Data Assurance（DA）を使用する場合、プライマリボリュームとセカンダリボリュームでDA設定を同じにする必要があります。

