---
permalink: sm-mirroring/synchronous-mirroring-activation.html 
sidebar: sidebar 
keywords: synchronous, mirror, activation 
summary: 同期ミラーリング機能は、最初の同期ミラーペアがストレージアレイに作成されたときに自動的にアクティブ化されます。 
---
= 同期ミラーリングのアクティブ化
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
同期ミラーリング機能は、最初の同期ミラーペアがストレージアレイに作成されたときに自動的にアクティブ化されます。

同期ミラーリング機能がアクティブ化されると、System Managerは次の処理を実行します。

* コントローラのHICで最も大きい番号のポートをデータ送信のミラーリング用に予約します。
+
このポートで受信したI/O要求は、ミラーペアに含まれるセカンダリボリュームのリモートの優先コントローラ所有者からのみ承認されます。（プライマリボリュームにおける予約が許可されます）。

* コントローラごとに1つずつ、リザーブ容量用ボリュームを2つ作成します。これは、コントローラのリセットおよびその他の一時的な中断からリカバリするための書き込み情報のロギングに使用されます。
+
各ボリュームの容量は128MiBです。ただし、ボリュームがプールに配置されている場合は、ボリュームごとに4GiBが予約されます。



同期ミラーリング機能では、特定のストレージアレイでサポートされるボリュームの数に制限があります。同期ミラーリングをアクティブ化する前に、お使いのストレージアレイに設定されているボリュームの数がサポートされている制限よりも少ないことを確認してください。同期ミラーリングがアクティブな場合は、作成済みの2つのリザーブ容量ボリュームがボリュームの制限に含まれます。

あとで同期ミラーリングを非アクティブ化する必要がある場合は、メニューから「Storage [Synchronous Mirroring]>[Uncommon Tasks]> Deactivate」に移動します。
