---
permalink: sm-hardware/configure-nvme-over-roce-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, roce, ports 
summary: コントローラにNVMe over RoCE（RDMA over Converged Ethernet）用の接続が含まれている場合は、ハードウェアページまたはシステムページからNVMeポートを設定できます。 
---
= NVMe over RoCEポートを設定します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラにNVMe over RoCE（RDMA over Converged Ethernet）用の接続が含まれている場合は、ハードウェアページまたはシステムページからNVMeポートを設定できます。

.作業を開始する前に
* コントローラにNVMe over RoCEホストポートが搭載されている必要があります。そうでないと、System ManagerでNVMe over RoCE設定を使用できません。
* ホスト接続のIPアドレスを確認しておく必要があります。


.このタスクについて
NVMe over RoCE設定には、ハードウェアページまたはメニューからアクセスできます。Settings [System]。このタスクでは、[*Hardware*]ページからポートを設定する方法について説明します。

[NOTE]
====
NVMe over RoCE の設定と機能は、ストレージアレイのコントローラに NVMe over RoCE ポートが搭載されている場合にのみ表示されます。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示されている場合は、 * シェルフの背面を表示 * をクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. NVMe over RoCE ポートを設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. NVMe over RoCE ポートの設定 * を選択します。
+
Configure NVMe over RoCE Ports（NVMe over RoCEポートの設定）ダイアログボックスが開きます。

. ドロップダウンリストで、設定するHICポートを選択します。
. 「 * 次へ * 」をクリックします。
+
すべてのポート設定を表示するには、ダイアログボックスの右側にある[詳細ポート設定を表示]リンクをクリックします。

+
.フィールドの詳細
[%collapsible]
====
|===
| ポートの設定 | 説明 


 a| 
イーサネットポート速度の設定
 a| 
ポートのSFPの速度と同じ速度を選択します。



 a| 
IPv4 を有効にする / IPv6 を有効にする
 a| 
一方または両方のオプションを選択して、 IPv4 ネットワークと IPv6 ネットワークのサポートを有効にします。


NOTE: ポートへのアクセスを無効にする場合は、両方のチェックボックスを選択解除します。



 a| 
MTUサイズ（Show more port settingsをクリックして使用可能）
 a| 
必要に応じて、 Maximum Transmission Unit （ MTU ；最大伝送ユニット）の新しいサイズをバイト単位で入力します。

デフォルトの Maximum Transmission Unit （ MTU ；最大転送単位）サイズは 1500 バイト / フレームです。1500~9000 の値を入力する必要があります。

|===
====
+
IPv4を有効にするを選択した場合は、次へをクリックするとIPv4設定を選択するダイアログボックスが開きます。IPv6を有効にするを選択した場合は、次へをクリックすると、IPv6設定を選択するためのダイアログボックスが開きます。両方のオプションを選択した場合は、最初にIPv4設定のダイアログボックスが開き、次へをクリックすると、IPv6設定のダイアログボックスが開きます。

. IPv4 と IPv6 、またはその両方を自動または手動で設定します。
+
.フィールドの詳細
[%collapsible]
====
|===
| ポートの設定 | 説明 


 a| 
自動的に設定を取得します
 a| 
設定を自動的に取得するには、このオプションを選択します。



 a| 
静的な設定を手動で指定します
 a| 
このオプションを選択した場合は、フィールドに静的アドレスを入力します。（必要に応じて、住所をカットアンドペーストしてフィールドに貼り付けることもできます）。 IPv4の場合は、ネットワークのサブネットマスクとゲートウェイも指定します。IPv6 の場合は、ルーティング可能な IP アドレスとルータの IP アドレスも指定します。

|===
====
. [ 完了 ] をクリックします。

