---
permalink: sm-hardware/drive-terminology.html 
sidebar: sidebar 
keywords: drive, terminology 
summary: ストレージアレイに関連するドライブの用語を次に示します。 
---
= ドライブの用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連するドライブの用語を次に示します。

|===
| コンポーネント | 説明 


 a| 
ダ
 a| 
Data Assurance（DA）は、ホストとストレージアレイの間でデータをやり取りするときに発生する可能性があるエラーをチェックして修正する機能です。Data Assuranceは、Fibre ChannelなどのDAに対応したI/Oインターフェイスを使用するホストで、プールまたはボリュームグループのレベルで有効にすることができます。



 a| 
ドライブセキュリティ機能
 a| 
ドライブセキュリティは、 Full Disk Encryption （ FDE ）ドライブまたは連邦情報処理標準（ FIPS ）ドライブを使用してセキュリティを強化するストレージアレイの機能です。これらのドライブにドライブセキュリティ機能を使用すると、データにアクセスするためのセキュリティキーが必要になります。ドライブをアレイから物理的に取り外した場合、別のアレイに取り付けるまでは動作しなくなり、取り付けた時点で正しいセキュリティキーが提供されるまではセキュリティロック状態になります。



 a| 
ドライブシェルフ
 a| 
ドライブシェルフは、拡張シェルフとも呼ばれ、一連のドライブと2つの入出力モジュール（IOM）が搭載されます。IOMには、ドライブシェルフをコントローラシェルフまたはその他のドライブシェルフに接続するSASポートが搭載されています。



 a| 
FDEドライブ
 a| 
Full Disk Encryption（FDE）ドライブは、ハードウェアレベルでディスクドライブの暗号化を実行します。ハードドライブに搭載されたASICチップにより、書き込み時にデータが暗号化され、読み取り時に復号化されます。



 a| 
FIPSドライブ
 a| 
FIPSドライブは、連邦情報処理標準（FIPS）140-2レベル2に準拠しています。基本的な概念はFDEドライブと同じですが、米国政府の基準に従って強力な暗号化アルゴリズムと暗号化方式を実装しています。FIPSドライブにはFDEドライブよりも高度なセキュリティ基準が採用されています。



 a| 
HDD
 a| 
ハードディスクドライブ（ HDD ）は、磁気コーティングを施した金属製の回転式ディスクを使用するデータストレージデバイスです。



 a| 
ホットスペアドライブ
 a| 
ホットスペアは、RAID 1、RAID 5、またはRAID 6のボリュームグループで、スタンバイドライブとして機能します。問題なく動作するドライブですが、データは格納されていません。ボリュームグループ内のドライブで障害が発生すると、障害が発生したドライブのデータがホットスペアに自動的に再構築されます。



 a| 
セキュリティ対応ドライブ
 a| 
セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。これらのドライブでは、書き込み時にデータが暗号化され、読み取り時に復号化されます。ドライブセキュリティ機能を使用したセキュリティの強化に使用できるため、これらのドライブはsecured_capable_とみなされます。これらのドライブを使用するボリュームグループやプールでドライブセキュリティ機能を有効にすると、ドライブはsecure-_enabled_になります。



 a| 
セキュリティ有効ドライブ
 a| 
セキュリティ有効ドライブは、ドライブセキュリティ機能で使用されます。ドライブセキュリティ機能を有効にし、かつsecured_caped_drivesのプールまたはボリュームグループにドライブセキュリティを適用すると、ドライブはsecure__enable__になります。読み取りおよび書き込みアクセスは、正しいセキュリティキーが設定されたコントローラからしか実行できません。この追加のセキュリティ機能により、ストレージアレイから物理的に取り外されたドライブ上のデータへの不正アクセスを防止できます。



 a| 
（ SAS ）。
 a| 
Serial Attached SCSI （ SAS ）は、コントローラをディスクドライブに直接リンクするポイントツーポイントのシリアルプロトコルです。



 a| 
SATA
 a| 
Serial Advanced Technology Attachment（SATA）ドライブは、シリアルシグナリングテクノロジに基づく標準に準拠しています。シリアルリンクは、最低4本のワイヤを持つ1本のケーブルを使用して、デバイス間にポイントツーポイント接続を確立します。SATAは、従来のパラレルテクノロジよりもコンパクトで信頼性が高く高速なデータ転送テクノロジです。



 a| 
SSD の場合
 a| 
ソリッドステートディスク（ SSD ）は、ソリッドステートメモリ（フラッシュ）を使用してデータを永続的に格納するデータストレージデバイスです。SSD は従来のハードドライブをエミュレートしたものであり、ハードドライブと同じインターフェイスで利用できます。

|===