---
permalink: sm-settings/certificate-terminology.html 
sidebar: sidebar 
keywords: certificate, terminology 
summary: ストレージアレイに関連する証明書の用語を次に示します。 
---
= 証明書の用語
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイに関連する証明書の用語を次に示します。

|===
| 期間 | 説明 


 a| 
できます
 a| 
認証局（CA）は、インターネットセキュリティのためにデジタル証明書と呼ばれる電子文書を発行する信頼されたエンティティです。証明書でWebサイトの所有者を識別することにより、クライアントとサーバの間のセキュアな接続が確立されます。



 a| 
CSR
 a| 
証明書署名要求（CSR）は、申請者から認証局（CA）に送信されるメッセージです。CSRは、CAが証明書の問題 に必要な情報を検証します。



 a| 
証明書
 a| 
証明書はセキュリティ上の目的でサイトの所有者を識別するもので、攻撃者による偽装を防止します。証明書には、サイトの所有者に関する情報と、その情報について証明（署名）する信頼されたエンティティのIDが含まれます。



 a| 
クライアント証明書
 a| 
セキュリティキー管理のために、クライアント証明書はストレージアレイのコントローラを検証し、キー管理サーバがコントローラのIPアドレスを信頼できるようにします。



 a| 
キー管理サーバ証明書
 a| 
セキュリティキー管理のために、キー管理サーバ証明書はサーバを検証し、ストレージアレイがサーバのIPアドレスを信頼できるようにします。



 a| 
管理証明書
 a| 
管理証明書は、認証局（CA）によって承認され、Webアプリケーションへのセキュアなアクセスを許可します。「署名済み証明書」とも呼ばれます。



 a| 
OCSPサーバ
 a| 
Online Certificate Status Protocol（OCSP）サーバは、スケジュールされた有効期限の前に認証局（CA）が証明書を失効させたかどうかを確認し、証明書が失効している場合はユーザがサーバにアクセスできないようにします。



 a| 
自己署名証明書
 a| 
自己署名証明書はコントローラに事前にロードされています。サイト接続が自己署名されている場合、Webアプリケーションに進む前に警告メッセージが表示されます。



 a| 
信頼された証明書
 a| 
認証局（CA）が発行した信頼された証明書は、証明書階層の最上位にある既知の証明書です。「ルート証明書」とも呼ばれます。

|===