---
permalink: sm-settings/configure-nvme-over-infiniband-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, infiniband, ports 
summary: コントローラにNVMe over InfiniBand接続が搭載されている場合は、ハードウェアページまたはシステムページでNVMeポートを設定できます。 
---
= NVMe over InfiniBandポートを設定する
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラにNVMe over InfiniBand接続が搭載されている場合は、ハードウェアページまたはシステムページでNVMeポートを設定できます。

.作業を開始する前に
* コントローラにNVMe over InfiniBandホストポートが搭載されている必要があります。そうでないと、System ManagerでNVMe over InfiniBand設定を使用できません。
* ホスト接続のIPアドレスを確認しておく必要があります。


.このタスクについて
NVMe over InfiniBand構成には、* Hardware *ページまたはメニューからアクセスできます：Settings [ System ]。このタスクでは、[*Hardware*]ページからポートを設定する方法について説明します。

[NOTE]
====
NVMe over InfiniBandの設定と機能は、ストレージアレイのコントローラにNVMe over InfiniBandポートが搭載されている場合にのみ表示されます。

====
.手順
. 「 * ハードウェア * 」を選択します。
. 図にドライブが表示されている場合は、 * シェルフの背面を表示 * をクリックします。
+
図の表示が切り替わり、ドライブではなくコントローラが表示されます。

. NVMe over InfiniBandポートを設定するコントローラをクリックします。
+
コントローラのコンテキストメニューが表示されます。

. Configure NVMe over InfiniBand ports] を選択します。
+
Configure NVMe over InfiniBand Ports * （ NVMe over InfiniBand ポートの設定 * ）ダイアログボックスが開きます。

. ドロップダウンリストで設定するHICポートを選択し、ホストのIPアドレスを入力します。
. [*Configure*] をクリックします。
. 設定を完了したら、「* Yes」をクリックしてNVMe over InfiniBandポートをリセットします。

