---
permalink: sm-settings/how-certificates-work-sam.html 
sidebar: sidebar 
keywords: ca certificates, csr files 
summary: 認証局（CA）は、インターネットセキュリティのためにデジタル証明書と呼ばれる電子文書を発行する信頼されたエンティティです。証明書でWebサイトの所有者を識別することにより、クライアントとサーバの間のセキュアな接続が確立されます。 
---
= CA証明書の仕組み
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
認証局（CA）は、インターネットセキュリティのためにデジタル証明書と呼ばれる電子文書を発行する信頼されたエンティティです。証明書でWebサイトの所有者を識別することにより、クライアントとサーバの間のセキュアな接続が確立されます。

ブラウザを開いてコントローラの管理ポート経由でSystem Managerに接続しようとすると、ストレージアレイのコントローラが信頼できるソースであるかどうかが確認されます。コントローラのデジタル証明書が見つからない場合、ブラウザは認識された権限で署名されていないことを警告し、続行するかどうかを確認するメッセージを表示します。このアラートが表示されないようにするには、署名入りのデジタル証明書をCAから取得する必要があります。

ドライブセキュリティ機能を持つ外部キー管理サーバを使用している場合は、そのサーバとコントローラの間の認証用の証明書を作成することもでき、また、ストレージアレイの自己署名証明書を使用することもできます。

信頼できる認証局のデジタル証明書を使用するには、次の手順が必要です。

. メニュー「Settings [ Certificates ]」に移動します。ユーザーログインにはSecurity Admin権限が含まれている必要があります。含まれていない場合、* Certificates *がページに表示されません。
. コントローラごと、またはキー管理サーバ用に、証明書署名要求（CSR）を作成します。
. CSRファイルをCAに送信し、証明書が送信されるまで待ちます。
. 信頼できる（中間およびルート）証明書をCAからインポートします。これらの証明書は、CA階層の信頼ポイントを確立します。
. 各コントローラまたはキー管理サーバの署名入りの管理証明書をインポートします。

