---
permalink: sm-settings/step-1-complete-a-csr.html 
sidebar: sidebar 
keywords: complete, ca certificate, signing, request, csr, controllers 
summary: ストレージアレイのコントローラの認証局（CA）証明書を受け取るには、まずストレージアレイ内のコントローラごとに証明書署名要求（CSR）ファイルを生成する必要があります。 
---
= コントローラのCA証明書署名要求（CSR）を作成します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイのコントローラの認証局（CA）証明書を受け取るには、まずストレージアレイ内のコントローラごとに証明書署名要求（CSR）ファイルを生成する必要があります。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。


このタスクでは、コントローラの署名付き管理証明書を受け取るためにCAに送信する.CSRファイル（証明書署名要求）を生成する方法について説明します。組織に関する情報とともに、コントローラのIPアドレスまたはDNS名を指定する必要があります。このタスクでは、ストレージアレイにコントローラが1つしかない場合は.CSRファイルが1つ、コントローラが2つある場合は2つ生成されます。

.手順
. メニューから[設定][証明書]を選択します。
. [*アレイ管理*]タブで、[* CSR全体*]を選択します。
+
[NOTE]
====
2台目のコントローラの自己署名証明書を受け入れるよう求めるダイアログボックスが表示された場合は、*自己署名証明書を受け入れる*をクリックして続行します。

====
. 次の情報を入力し、[次へ*]をクリックします。
+
** *組織*--会社または組織の正式名称。Inc.やCorp.などの接尾辞も含めて入力してください
** *組織単位（オプション）*--証明書を処理している組織の部門。
** *市区町村*--ストレージアレイまたは事業の所在地である市区町村。
** *都道府県（オプション）*-ストレージアレイまたは事業の所在地である都道府県。
** *国のISOコード*--自国を表す2桁のISO（国際標準化機構）コード（USなど）。


+
[CAUTION]
====
一部のフィールドには、コントローラのIPアドレスなどの適切な情報があらかじめ入力されています。事前入力された値は、明らかな間違いでないかぎり変更しないでください。たとえば、CSRをまだ作成していない場合、コントローラのIPアドレスは「localhost」に設定されます。 この場合は、「localhost」をコントローラのDNS名またはIPアドレスに変更する必要があります。

====
. ストレージアレイ内のコントローラAに関する次の情報を確認または入力します。
+
** *コントローラAの共通名*--コントローラAのIPアドレスまたはDNS名がデフォルトで表示されますこのアドレスが正しいことを確認してください。ブラウザでSystem Managerにアクセスする際に入力したアドレスと正確に一致している必要があります。
** *コントローラAの代替IPアドレス*-共通名がIPアドレスの場合は、コントローラAの追加のIPアドレスまたはエイリアスをオプションで入力できます複数指定する場合は、カンマで区切って入力します。
** *コントローラAの代替DNS名*--共通名がDNS名の場合は、コントローラAの追加のDNS名を入力します複数指定する場合は、カンマで区切って入力します。代替DNS名がない場合は、最初のフィールドに入力したDNS名をここにコピーします。ストレージアレイにコントローラが1台しかない場合は、「完了」ボタンを使用できます。ストレージアレイにコントローラが2台ある場合は、* Next *ボタンを使用できます。


+
[NOTE]
====
CSR要求を最初に作成するときは、[この手順をスキップ]リンクをクリックしないでください。このリンクは、エラーからリカバリする場合に使用します。CSR要求が一方のコントローラで失敗し、もう一方のコントローラで失敗することがあります。このリンクを使用すると、コントローラAでCSRがすでに定義されている場合はその作成をスキップし、コントローラBでCSRを再作成する次の手順に進むことができます

====
. コントローラが1台しかない場合は、[完了]をクリックします。コントローラが2台ある場合は、[次へ]をクリックしてコントローラBの情報を入力し（上記と同じ）、[完了]をクリックします。
+
シングルコントローラの場合は、1つの.CSRファイルがローカルシステムにダウンロードされます。デュアルコントローラの場合は、2つの.CSRファイルがダウンロードされます。ダウンロードフォルダの場所は、ブラウザによって異なります。

. .CSRファイルをCAに送信します。


デジタル証明書を受け取ったら、CAから送られてきた該当する証明書ファイルをインポートします。
