---
permalink: sm-settings/step-2-import-certificates-for-key-management-server.html 
sidebar: sidebar 
keywords: import, key, management, server, certificates 
summary: 外部キー管理のために、ストレージアレイとキー管理サーバが互いに信頼関係を確立できるように、2つのエンティティの間の認証用に証明書をインポートします。証明書には2種類あります。クライアント証明書はコントローラを検証し、キー管理サーバ証明書はサーバを検証します。 
---
= キー管理サーバ証明書をインポート
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
外部キー管理のために、ストレージアレイとキー管理サーバが互いに信頼関係を確立できるように、2つのエンティティの間の認証用に証明書をインポートします。証明書には2種類あります。クライアント証明書はコントローラを検証し、キー管理サーバ証明書はサーバを検証します。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。
* ストレージアレイでクライアント証明書を使用できる必要があります。
+
[NOTE]
====
クライアント証明書は、キー管理サーバがコントローラのIPアドレスを信頼できるよう、ストレージアレイのコントローラを検証します。クライアント証明書を取得するには、ストレージアレイのCSRを作成して、キー管理サーバにアップロードする必要があります。サーバから、クライアント証明書を生成します。

====
* キー管理サーバ証明書が必要です。
+
[NOTE]
====
キー管理サーバ証明書は、ストレージアレイがサーバのIPアドレスを信頼できるように、サーバを検証します。キー管理サーバ証明書を取得するには、キー管理サーバから生成する必要があります。

====


このタスクでは、ストレージアレイコントローラとキー管理サーバの間の認証用に証明書ファイルをアップロードする方法について説明します。

.手順
. メニューから[設定][証明書]を選択します。
. [*キー管理*]タブで、[*インポート*]を選択します。
+
証明書ファイルをインポートするためのダイアログボックスが表示されます。

. ファイルを選択するには、*参照*ボタンをクリックします。
+
ダイアログボックスにファイル名が表示されます。

. [* インポート * ] をクリックします。
+
ファイルがアップロードされて検証されます。


