---
permalink: sm-settings/step-1-complete-and-submit-csr-for-authentication-with-a-key-server.html 
sidebar: sidebar 
keywords: complete, ca certificate, signing, request, csr, key server 
summary: キー管理サーバの認証局（CA）証明書を受け取るには、まず証明書署名要求（CSR）ファイルを生成する必要があります。 
---
= キーサーバのCA証明書署名要求（CSR）を実行します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キー管理サーバの認証局（CA）証明書を受け取るには、まず証明書署名要求（CSR）ファイルを生成する必要があります。

.作業を開始する前に
* Security Adminの権限を含むユーザプロファイルでログインする必要があります。そうしないと、証明書の機能は表示されません。


.このタスクについて
このタスクでは、キー管理サーバの署名済み証明書を受け取るためにCAに送信する.CSRファイル（証明書署名要求）を生成する方法について説明します。このタスクでは、組織に関する情報を指定する必要があります。

.手順
. メニューから[設定][証明書]を選択します。
. [*キー管理*]タブで、[* CSR全体*]を選択します。
. 次の情報を入力します。
+
** *共通名*--証明書ファイルに表示されるストレージアレイ名など、このCSRを識別する名前。
** *組織*--会社または組織の正式名称。Inc.やCorp.などの接尾辞も含めて入力してください
** *組織単位（オプション）*--証明書を処理している組織の部門。
** *市区町村*--組織の所在地である市区町村。
** *都道府県(オプション)*--組織の所在地である都道府県。
** *国のISOコード*--組織の所在地である米国などの2桁のISO（国際標準化機構）コード。


. [ * ダウンロード ] をクリックします。
+
.CSRファイルがローカルシステムに保存されます。

. .CSRファイルをCAに送信します。


.完了後
キー管理サーバからクライアント証明書とサーバ証明書を取得したら、ストレージアレイコントローラで認証するためにそれらの証明書をインポートします。
