---
permalink: sm-settings/view-nvme-over-fabrics-statistics-support.html 
sidebar: sidebar 
keywords: view, nvme, over, fabrics, statistics 
summary: ストレージアレイへのNVMe over Fabrics接続に関するデータを表示できます。 
---
= NVMe over Fabricsの統計を表示します
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージアレイへのNVMe over Fabrics接続に関するデータを表示できます。

System Managerには、次のタイプのNVMe over Fabrics統計が表示されます。統計はすべて読み取り専用で、設定することはできません。

* * nvmeサブシステム統計*--タイムアウトや接続エラーなど、NVMeコントローラの統計が表示されます。
* *rdma Interface statistics *--送受信されたパケット情報を含むRDMAインタフェースの統計情報を提供します。


これらの統計はそれぞれ、統計の生データまたはベースライン統計として表示できます。統計の生データは、コントローラの起動以降に収集されたすべての統計です。ベースライン統計は、ベースライン時間の設定以降に収集されたポイントインタイムの統計です。

NVMe over Fabrics統計には、システムページ（メニュー：設定[システム]）またはサポートページからアクセスできます。ここでは、Supportページから統計情報にアクセスする方法について説明します。

.手順
. メニューを選択します。Support（サポートセンター）> Diagnostics（診断）タブ。
. View NVMe over Fabrics Statistics *を選択します。
. ベースラインを設定するには、*新しいベースラインを設定*をクリックします。
+
ベースラインを設定すると、統計を収集するための新しい開始ポイントが設定されます。すべてのNVMe統計に同じベースラインが使用されます。


